version: '2'
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
  hasura:
    build:
      context: ./backend
      dockerfile: Dockerfile.hasura
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: "postgres://postgres:secret@db:5432"
      PORT: 5000
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "development_key_123456789_123456789"}'
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
    depends_on:
      - db
  hbp:
    build:
      context: ./backend
      dockerfile: Dockerfile.hbp
    ports:
      - 5001:5001
    environment:
      PORT: 5001
      HASURA_GRAPHQL_ENDPOINT: http://hasura:5000/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "development_key_123456789_123456789"}'
    depends_on:
      - hasura
    command: node src/index.js
